---

# - name: touch bastion known_hosts file
#   file:
#     path: ~/.ssh/known_hosts
#     state: touch
#     mode: "0600"
#   delegate_to: "{{bastion_public_ip}}"
#   remote_user: "{{amazon_user}}"
