---

- name: add node dns
  route53:
    zone: "{{dns_zone}}"
    record: "node{{item.index}}.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ nodes }}"
