---

- name: checkout openshift-aws-setup repo
  git:
    repo: "https://github.com/ecwpz91/openshift-aws-setup"
    dest: "~{{amazon_user}}/openshift-aws-setup"
    version: "develop"
    force: yes

- name: copy amazon key pair
  copy:
   src: "{{lookup('env','HOME')}}/.ssh/{{aws_key_pair}}"
   dest: "~{{amazon_user}}/.ssh/{{aws_key_pair}}"
   mode: 0400

- name: create ssh config file
  template:
    src: "../files/config"
    dest: "~{{amazon_user}}/.ssh/config"
    mode: 0600

- name: copy aws config file
  copy:
   src: vars/aws-config.yml
   dest: "~{{amazon_user}}/openshift-aws-setup/vars/aws-config.yml"

- name: copy aws cache file
  copy:
   src: vars/aws-cache.yml
   dest: "~{{amazon_user}}/openshift-aws-setup/vars/aws-cache.yml"

- name: set access key id environment variable
  lineinfile: dest=~{{amazon_user}}/.bashrc
              regexp='^export AWS_ACCESS_KEY_ID'
              line='export AWS_ACCESS_KEY_ID={{lookup('env','AWS_ACCESS_KEY_ID')}}'

- name: set secret key environment variable
  lineinfile: dest=~{{amazon_user}}/.bashrc
              regexp='^export AWS_SECRET_ACCESS_KEY'
              line='export AWS_SECRET_ACCESS_KEY={{lookup('env','AWS_SECRET_ACCESS_KEY')}}'

- name: run openshift-aws-setup playbook
  command: ./openshift-playbook-run.sh -e rhsm_key_id={{rhsm_key_id}} -e rhsm_org_id={{rhsm_org_id}}
  args:
   chdir: "~{{amazon_user}}/openshift-aws-setup"
