---

- name: provision vpc
  ec2_vpc_net:
    name: "{{namespace}}-vpc"
    cidr_block: "{{ vpc_cidr }}"
    tags:
      Name: "{{namespace}}-vpc"
      namespace: "{{namespace}}"
    region: "{{ region }}"
    state: "present"
  register: vpc_facts

- name: provision internet gateway
  ec2_vpc_igw:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    region: "{{ region }}"
    state: "present"
  register: igw_facts

- name: provision subnet
  ec2_vpc_subnet:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    cidr: "{{subnet_cidr}}"
    tags:
      Name: "{{namespace}}-subnet"
      namespace: "{{namespace}}"
    region: "{{ region }}"
    state: "present"
  register: subnet_facts

- name: set subnet facts
  set_fact:
   subnet_id: "{{subnet_facts['subnet']['id']}}"

- name: set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    tags:
      Name: "{{namespace}}-route"
      namespace: "{{namespace}}"
    subnets:
      - "{{subnet_id}}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{igw_facts['gateway_id']}}"
    region: "{{ region }}"
    state: "present"
  register: route_facts

- name: set vpc facts
  set_fact:
   vpc_id: "{{vpc_facts['vpc']['id']}}"

- name: set availability zone facts
  set_fact:
    availability_zone: "{{subnet_facts['subnet']['availability_zone']}}"
