---

#############################################################
# Provision AWS Infrastructure
#############################################################
- name: provision openshift infrastructure
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

  roles:
  - define-derived-vars
  - setup-vms
  - setup-vms-master
  - setup-vms-node
  - setup-dns
  - setup-dns-master
  - setup-dns-nodes
  - setup-ssh
  - setup-ssh-master
  - setup-ssh-nodes

  pre_tasks:
    - name: verify ansible version
      assert:
        that:
          - "ansible_version.major == 2"
          - "ansible_version.minor >= 4"
        msg: "This script is only supported with the 2.4.1 version or later of Ansible"

    - name: verify gluster prerequisites
      assert:
        that:
          - "app_nodes >= 3"
        msg: "To install gluster you must have at least three app nodes defined, only {{app_nodes}} defined in variables"
      when: install_gluster

    - fail: msg="Variables required to register subscriptions are missing, please confirm that either rhsm_username, rhsm_password and rhsm_pool OR rhsm_key_id and rhsm_org_id is defined"
      when: (deployment_type == 'openshift-enterprise') and not (((rhsm_username is defined) and (rhsm_password is defined) and (rhsm_pool is defined)) or ((rhsm_key_id is defined) and (rhsm_org_id is defined)))

#############################################################
# Register/Update Virtual Machines
#############################################################
- name: setup virtual machine hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

- name: register and update virtual machines
  hosts: created_vms
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:
  - {role: register-virtual-machines, when: deployment_type == 'openshift-enterprise'}
  - update-virtual-machines
  - openshift-pre-reqs

#############################################################
# Install Gluster Prerequisites
#############################################################
- name: setup gluster requirements
  hosts: master
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  roles:
  - {role: gluster-master-prereqs, when: install_gluster}

- name: Setup gluster node prereqs
  hosts: gluster
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  roles:
  - {role: gluster-node-prereqs, when: install_gluster}

#############################################################
# Install OpenShift Platform
#############################################################
- name: install openshift environment
  hosts: localhost
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
#    nodes: "{{ lookup('file','nodes.json') | from_json }}"

  roles:
  - define-derived-vars
  - openshift-install
  - {role: grafana-install, when: install_grafana}

#############################################################
# Post- Installation Tasks
#############################################################
- name: configure openshift environment
  hosts: master
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  post_tasks:
   - name: print certificate information
     debug:
       msg:
         - 'SSL certificates have been generated using letsencrypt and backed up locally:'
         - '\tcerts/letsencrypt\n'
         - 'Note that letsencrypt is rate limited to 20 requests a week and SSL certificates last for 90 days.'
         - 'If you need to run the playbook again, consider using the certificates backed up locally by'
         - 'setting the following variables in vars/aws_config.yml'
         - '\tmaster_ssl_cert_file: "{{master_ssl_cert_file}}"'
         - '\tmaster_ssl_key_file: "{{master_ssl_key_file}}"'
         - '\master_ssl_ca_file: "{{master_ssl_ca_file}}"'
         - '\wildcard_ssl_cert_file: "{{wildcard_ssl_cert_file}}"'
         - '\twildcard_ssl_key_file: "{{wildcard_ssl_key_file}}"'
         - '\twildcard_ssl_fullchain_file: "{{wildcard_ssl_fullchain_file}}"'
     when: use_lets_encrypt

  roles:
  - define-derived-vars
  - pip-install
  - add-users
  - {role: update-ssl-cockpit, when: master_ssl_cert_file is defined}
  - {role: disable-service-catalog, when: disable_service_catalog}
  - {role: wetty-install, when: install_wetty}
