---

- name: create vars cache file
  file:
   path: vars/aws-cache.yml
   state: touch

- name: cache set facts
  blockinfile:
    path: vars/aws-cache.yml
    block: |
      subnet_id: {{subnet_id}}
      vpc_id: {{vpc_id}}
      availability_zone: {{availability_zone}}
      image: {{image}}
      device_name: {{device_name}}
      bastion_private_ip: {{bastion_private_ip}}
      bastion_public_ip: {{bastion_public_ip}}
      bastion_rsa_pub: {{bastion_rsa_pub}}

# - name: cache master facts
#   lineinfile: dest="vars/aws-cache.yml"
#               line={{ item.line }}
#               insertafter={{ item.insertafter }}
#   with_items:
#     - { line: "master_private_ip: {{ master_private_ip }}", insertafter: 'EOF' }
#     - { line: "master_public_ip: {{ master_public_ip }}", insertafter: 'master_private_ip: {{ master_private_ip|replace(".", "\.") }}' }
#     - { line: "master_private_dns_name: {{ master_private_dns_name }}", insertafter: 'master_public_ip: {{ master_public_ip|replace(".", "\.") }}' }

#[TODO]: Cache node facts

# - name: cache cert path facts
#   lineinfile: dest="vars/aws-cache.yml"
#               line={{ item.line }}
#               insertafter={{ item.insertafter }}
#   with_items:
#     - { line: "cert_path: {{ cert_path }}", insertafter: 'EOF' }
