---

#This security group allows intra-node communication on all ports with all protocols.
- name: create openshift-vpc
  ec2_group:
    name: "{{namespace}}-vpc"
    description: "Default security group that allows all instances in the VPC to talk to each other over any port and protocol."
    vpc_id: "{{vpc_id}}"
    region: "{{region}}"
    state: "present"
    rules:
      - proto: "-1"
        from_port: "0"
        to_port: "0"
        group_name: "{{namespace}}-vpc"
    rules_egress:
      - proto: "-1"
        from_port: "0"
        to_port: "0"
        group_name: "{{namespace}}-vpc"

#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: create openshift-public-ingress
  ec2_group:
    name: "{{namespace}}-public-ingress"
    description: "Security group that allows public ingress to instances, HTTP, HTTPS and more."
    vpc_id: "{{vpc_id}}"
    region: "{{region}}"
    state: "present"
    rules:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTP_PROXY
      - proto: "tcp"
        from_port: "8080"
        to_port: "8080"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      # HTTPS_PROXY
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
      # COCKPIT
      - proto: "tcp"
        from_port: "9090"
        to_port: "9090"
        cidr_ip: "0.0.0.0/0"
      # WETTY
      - proto: "tcp"
        from_port: "8888"
        to_port: "8888"
        cidr_ip: "0.0.0.0/0"
    rules_egress: []

#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: create openshift-public-egress
  ec2_group:
    name: "{{namespace}}-public-egress"
    description: "This security group allows public egress from the instances for HTTP and HTTPS, which is needed for yum updates, git access etc etc."
    vpc_id: "{{vpc_id}}"
    region: "{{region}}"
    state: "present"
    rules_egress:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
        # NTP/chrony
      - proto: "udp"
        from_port: "123"
        to_port: "123"
        cidr_ip: "0.0.0.0/0"
# Security group which allows SSH access to a host. Used for the bastion.
- name: create openshift-ssh
  ec2_group:
    name: "{{namespace}}-ssh"
    description: "Default security group that allows all instances in the VPC to talk to each other over any port and protocol."
    vpc_id: "{{vpc_id}}"
    region: "{{region}}"
    state: "present"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
    rules_egress: []
