---

- name: install required packages
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker-1.13.1"
      - "ntp"
      - "cockpit"
      - "dnsmasq"
    state: "present"
  register: task_result
  become: true

- name: install upstream packages
  yum:
    name:
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
    state: "present"
  register: task_result
  become: true
  when: deployment_type == 'origin'

- name: install atomic-openshift-utils
  yum:
    name:
      - "atomic-openshift-utils"
    state: "present"
  become: true
  when: (openshift_version | string) == "3.9"

- name: install openshift-ansible
  yum:
    name:
      - "openshift-ansible"
    state: "present"
  become: true
  when: (openshift_version | string) == "3.9"

- name: configure docker storage
  template:
    src: "../files/docker-storage-setup"
    dest: "/etc/sysconfig/docker-storage-setup"
  become: true

- name: configure docker storage
  command: "docker-storage-setup"
  become: true

- name: update docker options
  shell: "sed -i '/OPTIONS=.*/c\\OPTIONS=\"--selinux-enabled --insecure-registry 172.30.0.0/16\"' /etc/sysconfig/docker"
  become: true

- name: enable docker on boot
  systemd:
     name: docker
     enabled: yes
     state: started
  become: true

- name: reboot server immediately
  shell: "sleep 5 && /usr/bin/systemctl reboot"
  async: 1
  poll: 0
  become: true
  ignore_errors: yes
  when: task_result is changed

- name: wait for host to come back
  pause:
    minutes: 2
  when: task_result is changed
