---

- name: force unregister before register
  redhat_subscription:
    state: absent
  ignore_errors: yes
  become: true

- name: customer portal registration
  redhat_subscription:
    state: present
    username: "{{rhsm_username}}"
    password: "{{rhsm_password}}"
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_username is defined) and
        (rhsm_password is defined)

- name: activation key registration
  redhat_subscription:
    state: "present"
    activationkey: "{{ rhsm_key_id }}"
    org_id: "{{ rhsm_org_id }}"
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_key_id is defined) and
        (rhsm_org_id is defined)

- name: subscribe to pool
  shell: /usr/bin/subscription-manager attach --pool={{ rhsm_pool }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5
  ignore_errors: no
  become: true
  when: rhsm_pool is defined

- name: disable all repos
  shell: 'subscription-manager repos --disable="*"'
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  become: true

- name: enable required repos
  shell: 'subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-{{ocp_version}}-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"'
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  become: true

- name: enable additional repos
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  become: true
