---

- name: set master dns facts
  set_fact:
    public_master_dns: "{{ prefix_master_dns | default(None) }}{{ (prefix_master_dns == None) | ternary('', '.') }}{{ public_dns_zone }}"

- name: set master ssl facts
  set_fact:
    master_ssl_cert_file: "certs/letsencrypt/{{public_master_dns}}/fullchain.pem"
    master_ssl_key_file: "certs/letsencrypt/{{public_master_dns}}/privkey.pem"
    master_ssl_ca_file: "certs/letsencrypt/{{public_master_dns}}/cert.pem"
  when: use_lets_encrypt

- name: set wildcard ssl facts
  set_fact:
    wildcard_ssl_cert_file: "certs/letsencrypt/{{public_subdomain_prefix}}.{{public_dns_zone}}/fullchain.pem"
    wildcard_ssl_key_file: "certs/letsencrypt/{{public_subdomain_prefix}}.{{public_dns_zone}}/privkey.pem"
    wildcard_ssl_fullchain_file: "certs/letsencrypt/{{public_subdomain_prefix}}.{{public_dns_zone}}/fullchain.pem"
  when: use_lets_encrypt
