---

- name: copy ansible.cfg file
  copy:
    src: ../files/ansible.cfg
    dest: "~{{amazon_user}}/ansible.cfg"

- name: copy inventory for openshift istallation
  template:
    src: "../files/openshift_inventory.cfg"
    dest: "~{{amazon_user}}/openshift_inventory.cfg"

- name: checkout openshift ansible repo on bastion
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{amazon_user}}/openshift-ansible"
    version: "{{openshift_branch}}"
  when: deployment_type == 'origin'

- name: copy script for openshift installation
  template:
    src: "../files/install-openshift.sh"
    dest: "~{{amazon_user}}/install-openshift.sh"
    mode: 0775

- name: provide details to check installation
  debug:
   msg: "Check file install-openshift.log in Bastion 'ssh {{amazon_user}}@{{bastion_public_ip}}'"

- name: run openshift installation script
  command: './install-openshift.sh {{deployment_type}} |& tee install-openshift.log'
  args:
   chdir: "~{{amazon_user}}"
