---

- name: provision private dns zone
  route53_zone:
     zone: "{{dns_zone}}"
     state: "present"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{region}}"
     comment: "Internal zone for Openshift"
  register: aws_zone

- name: set private dns zone facts
  set_fact:
   private_zone: "{{aws_zone}}"
